server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carnivry
    username: root
    password: Root@5222
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect


driver-class-name: com.mysql.cj.jdbc.Driver

aes:
  encryption:
    key: this-is-test-key
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

