server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Carnivry
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true