server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carnivry
    username: root
    password: Root@5222
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

driver-class-name: com.mysql.cj.jdbc.Driver

