server:
  port: 8082
spring:
  neo4j:
    uri: bolt://localhost:7687
    data:
      neo4j:
        username: neo4j
        password: root
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true